# Transform

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

In [3]:
# Load the extracted data
df = pd.read_csv('../data/raw_tickets.csv')

# Preview first 5 rows
df.head()

C:\Users\coit25\AppData\Local\Temp\ipykernel_32676\4023778362.py:2: DtypeWarning: Columns (39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw_tickets.csv')

,ticketid,Ticket,CreationDate,LastUpdated,Type,State,Priority,Source,User,AssignedAgent,...,Agent EmailID,ClosureTime,SLA_Response_Time,SLA_Resolution_Time,LoginID,AA,TimeDifferenceMinutes,resp_minutes,resp_hrs,DD
0,26250,#26250,6/23/2023 3:19,6/23/2023 10:51,Application Support,Resolved by IT,Medium,Email,Microsoft Outlook,Ashok Wagh,...,ashok.wagh@hp.co.in,312d 0h 41m,3.0,24.0,NaN,60+ days,452.0,14.0,0.0,0.0
1,26249,#26249,6/23/2023 3:19,6/23/2023 10:51,Application Support,Resolved by IT,Medium,Email,Microsoft Outlook,Ashok Wagh,...,ashok.wagh@hp.co.in,312d 0h 41m,3.0,24.0,NaN,60+ days,452.0,14.0,0.0,0.0
2,26248,#26248,6/23/2023 3:19,6/23/2023 10:51,Application Support,Resolved by IT,Medium,Email,Microsoft Outlook,Ashok Wagh,...,ashok.wagh@hp.co.in,312d 0h 41m,3.0,24.0,NaN,60+ days,452.0,14.0,0.0,0.0
3,26247,#26247,6/23/2023 3:19,6/23/2023 10:51,Application Support,Resolved by IT,Medium,Email,Microsoft Outlook,Ashok Wagh,...,ashok.wagh@hp.co.in,312d 0h 41m,3.0,24.0,NaN,60+ days,452.0,14.0,0.0,0.0
4,26246,#26246,6/23/2023 3:19,6/23/2023 10:51,Application Support,Resolved by IT,Medium,Email,Microsoft Outlook,Ashok Wagh,...,ashok.wagh@hp.co.in,312d 0h 41m,3.0,24.0,NaN,60+ days,452.0,14.0,0.0,0.0

# Data Cleaning

In [4]:
# Check for Nulls
# Check missing values
df.isnull().sum().sort_values(ascending=False).head(10)

ClosureTime         9271
D                   9190
Deadline            9190
Days                9190
LoginID             9185
BusinessFunction    7773
BU                  7771
CaseCategory        7510
resp1               1322
resp_minutes        1288
dtype: int64

In [7]:
df.columns.tolist()

['ticketid',
 'ticket',
 'creationdate',
 'lastupdated',
 'type',
 'state',
 'priority',
 'source',
 'user',
 'assignedagent',
 'userlastnote',
 'icon',
 'subject',
 'bu',
 'businessfunction',
 'casecategory',
 'resolution',
 'fiscal_year',
 'quarter',
 'month',
 'ageing_bucket',
 'ageing',
 'day',
 'year_month_order',
 'yearmonth',
 'agent',
 'entity',
 'creationdatetest',
 'custombu',
 'ageing_lastupdated',
 'aging_bucket_last_updated',
 'deadline',
 'deadlinetotoday',
 'days',
 'resp1',
 'd',
 'devonly',
 'user_emailid',
 'agent_emailid',
 'closuretime',
 'sla_response_time',
 'sla_resolution_time',
 'loginid',
 'aa',
 'timedifferenceminutes',
 'resp_minutes',
 'resp_hrs',
 'dd']

In [10]:
# Clean column names for consistency
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('-', '_')
df.columns.tolist()

['ticketid',
 'ticket',
 'creationdate',
 'lastupdated',
 'type',
 'state',
 'priority',
 'source',
 'user',
 'assignedagent',
 'userlastnote',
 'icon',
 'subject',
 'bu',
 'businessfunction',
 'casecategory',
 'resolution',
 'fiscal_year',
 'quarter',
 'month',
 'ageing_bucket',
 'ageing',
 'day',
 'year_month_order',
 'yearmonth',
 'agent',
 'entity',
 'creationdatetest',
 'custombu',
 'ageing_lastupdated',
 'aging_bucket_last_updated',
 'deadline',
 'deadlinetotoday',
 'days',
 'resp1',
 'd',
 'devonly',
 'user_emailid',
 'agent_emailid',
 'closuretime',
 'sla_response_time',
 'sla_resolution_time',
 'loginid',
 'aa',
 'timedifferenceminutes',
 'resp_minutes',
 'resp_hrs',
 'dd']

In [11]:
date_cols = [
    'creationdate', 'lastupdated', 'deadline',
    'closuretime', 'creationdatetest', 'ageing_lastupdated'
]

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')

In [12]:
# Drop flags, icons, test/dev-only columns
columns_to_drop = ['icon', 'd', 'resp1', 'devonly', 'aa', 'dd']
df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

In [13]:
df.columns.tolist()

['ticketid',
 'ticket',
 'creationdate',
 'lastupdated',
 'type',
 'state',
 'priority',
 'source',
 'user',
 'assignedagent',
 'userlastnote',
 'subject',
 'bu',
 'businessfunction',
 'casecategory',
 'resolution',
 'fiscal_year',
 'quarter',
 'month',
 'ageing_bucket',
 'ageing',
 'day',
 'year_month_order',
 'yearmonth',
 'agent',
 'entity',
 'creationdatetest',
 'custombu',
 'ageing_lastupdated',
 'aging_bucket_last_updated',
 'deadline',
 'deadlinetotoday',
 'days',
 'user_emailid',
 'agent_emailid',
 'closuretime',
 'sla_response_time',
 'sla_resolution_time',
 'loginid',
 'timedifferenceminutes',
 'resp_minutes',
 'resp_hrs']

In [14]:
for col in ['bu', 'businessfunction', 'casecategory', 'custombu', 'entity']:
    df[col] = df[col].fillna('Unknown')

In [15]:
df['is_closed'] = df['closuretime'].notna().astype(int)

In [18]:
df['ticket_age_days'] = np.where(
    df['closuretime'].notna(),
    (df['closuretime'] - df['creationdate']).dt.days,
    (pd.Timestamp.now() - df['creationdate']).dt.days
)

In [19]:
df['resolution_time_hours'] = (df['closuretime'] - df['creationdate']).dt.total_seconds() / 3600

In [20]:
if 'resp_minutes' not in df.columns or df['resp_minutes'].isnull().any():
    df['resp_minutes'] = (df['lastupdated'] - df['creationdate']).dt.total_seconds() / 60

df['resp_hrs'] = df['resp_minutes'] / 60

In [21]:
# SLA breach if actual > allowed
df['sla_resolution_time'] = pd.to_numeric(df['sla_resolution_time'], errors='coerce')

df['sla_breach'] = np.where(
    (df['resolution_time_hours'].notna()) & (df['sla_resolution_time'].notna()),
    df['resolution_time_hours'] > df['sla_resolution_time'],
    np.nan
)

In [22]:
if 'priority' in df.columns:
    df['priority'] = df['priority'].str.lower().str.strip().replace({
        'p1': 'high', 'p2': 'medium', 'p3': 'low',
        'high priority': 'high', 'medium priority': 'medium', 'low priority': 'low'
    })

In [23]:
df

,ticketid,ticket,creationdate,lastupdated,type,state,priority,source,user,assignedagent,...,sla_response_time,sla_resolution_time,loginid,timedifferenceminutes,resp_minutes,resp_hrs,is_closed,ticket_age_days,resolution_time_hours,sla_breach
0,26250,#26250,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
1,26249,#26249,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
2,26248,#26248,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
3,26247,#26247,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
4,26246,#26246,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17701,37462,#37462,2023-10-23 10:52:00,2023-11-02 11:40:00,Application Support,Closed,medium,Website,Ankita Meshram,Ashok Wagh,...,3.0,24.0,coppc11,14448.0,14448.0,240.800000,0,647.0,NaN,NaN
17702,37414,#37414,2023-10-20 09:02:00,2024-01-22 12:10:00,Application Support,Closed,medium,Website,Amol Bhagwat,Ashok Wagh,...,3.0,24.0,coppc05,135548.0,135548.0,2259.133333,0,650.0,NaN,NaN
17703,37363,#37363,2023-10-18 14:08:00,2023-10-25 14:49:00,Application Support,Closed,medium,Website,Ankita Meshram,Ashok Wagh,...,3.0,24.0,coppc11,10121.0,10121.0,168.683333,0,651.0,NaN,NaN
17704,37297,#37297,2023-10-16 11:40:00,2023-12-06 16:35:00,Application Support,Closed,medium,Website,Anket Tekade,Ashok Wagh,...,3.0,24.0,coppc10,73735.0,73735.0,1228.916667,0,653.0,NaN,NaN
17705,37295,#37295,2023-10-16 11:25:00,2023-12-06 16:35:00,Application Support,Closed,medium,Website,Anket Tekade,Ashok Wagh,...,3.0,24.0,coppc10,73750.0,73750.0,1229.166667,0,654.0,NaN,NaN

In [28]:
df.to_csv('../data/tickets_transformed.csv', index=False)
print("âœ… Transformed dataset saved to /data/tickets_transformed.csv")

âœ… Transformed dataset saved to /data/tickets_transformed.csv

In [25]:
df[['ticketid', 'creationdate', 'closuretime', 'resolution_time_hours',
    'resp_minutes', 'sla_breach', 'priority', 'ticket_age_days']].head()

,ticketid,creationdate,closuretime,resolution_time_hours,resp_minutes,sla_breach,priority,ticket_age_days
0,26250,2023-06-23 03:19:00,NaT,NaN,452.0,NaN,medium,769.0
1,26249,2023-06-23 03:19:00,NaT,NaN,452.0,NaN,medium,769.0
2,26248,2023-06-23 03:19:00,NaT,NaN,452.0,NaN,medium,769.0
3,26247,2023-06-23 03:19:00,NaT,NaN,452.0,NaN,medium,769.0
4,26246,2023-06-23 03:19:00,NaT,NaN,452.0,NaN,medium,769.0

In [29]:
df.head()

,ticketid,ticket,creationdate,lastupdated,type,state,priority,source,user,assignedagent,...,sla_response_time,sla_resolution_time,loginid,timedifferenceminutes,resp_minutes,resp_hrs,is_closed,ticket_age_days,resolution_time_hours,sla_breach
0,26250,#26250,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
1,26249,#26249,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
2,26248,#26248,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
3,26247,#26247,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN
4,26246,#26246,2023-06-23 03:19:00,2023-06-23 10:51:00,Application Support,Resolved by IT,medium,Email,Microsoft Outlook,Ashok Wagh,...,3.0,24.0,NaN,452.0,452.0,7.533333,0,769.0,NaN,NaN